### ISSUE TITLE
Scrollbars not styled on Linux

### ISSUE THREAD

**Issue by eigan** [jmarquis/conduit-ui#1]
You could try to play around with this (added this to my custom stylesheet in the meantime)

``` less
.scrollbars-visible-always {
  /deep/ ::-webkit-scrollbar {
    width: 10px;
    height: 10px;
  }

  /deep/ ::-webkit-scrollbar-track,
  /deep/ ::-webkit-scrollbar-corner {
    background: rgba(0,0,0,0.1);
  }

  /deep/ ::-webkit-scrollbar-thumb {
    background: rgba(0,0,0,0.2);
    border-radius: 5px;
    box-shadow: 0 0 1px black inset;
  }
}
```

Taken from [atom-dark-ui](https://github.com/atom/atom-dark-ui/blob/master/styles/atom.less#L11)

Great theme :)
